# Change these first
owner: abulgit # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Glitch
    url: https://bknd-api.glitch.me/ping
    method: GET
    expectedStatusCodes:
      - 200
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there

  baseUrl: /Uptime
  theme: night
  logoUrl: https://github.githubassets.com/images/modules/site/features/actions-icon-actions.svg
  name: Upptime
  introTitle: "**Status For Websites**"
  introMessage: Rael time Status powered entirely by GitHub.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
